### ISSUE TITLE
PHP 8.0 への対応

### ISSUE THREAD

**Issue by gatespace** [kuno1/theme-customizer#6]
PHP8.0環境で `composer update` を実行するとインストールできません。
```
    - Root composer.json requires kunoichi/theme-customizer ^1.1 -> satisfiable by kunoichi/theme-customizer[1.1.0].
    - kunoichi/theme-customizer 1.1.0 requires php ^5.6|^7.0 -> your php version (8.0; overridden via config.platform, actual: 8.1.11) does not satisfy that requirement.
```

php 8.0への 対応予定はありますか？

＊依存パッケージも同じようにPHP8.0への対応が必要だと思います。
https://github.com/hametuha/string-utility

**Comment by fumikito** [comment]
closed via https://github.com/kuno1/theme-customizer/releases/tag/1.2.0

@gatespace
